### PR TITLE
The computation of the badge size is flawed in some circumstances: The space surrounding the label (and sometimes - by a lesser extent - also the value) is sometimes to small and some other times to large.

### PR DESCRIPTION
**Pull request by elbosso**
I use the solution to create dynamic badges in gitlab as the example screenshot shows:
image
image

But the screenshot also shows that the space surrounding the label (and sometimes - by a lesser extent - also the value) is sometimes to small and some other times to large.

I therefore made some small changes - also introducing two newdependencies - that not only mitigate this issue but also allow to use any font installed on the system for the badges. It essentially computes the real extent of the text using the specified font - achieving results like these (the results are added as attachments):
```
python3 ./anybadge.py -l "issues not touched since last weeks" -v 100 -s "%" -f TimesNewRoman.svg -o -n "Times New Roman"
python3 ./anybadge.py -l "issues not touched since last weeks" -v 100 -s "%" -f DejaVuSans.svg -o -n "DejaVu Sans"
python3 ./anybadge.py -l "issues not touched since last weeks" -v 100 -s "%" -f Arial.svg -o -n "Arial"
python3 ./anybadge.py -l "issues not touched since last weeks" -v 100 -s "%" -f FreeMono.svg -o -n "FreeMono"
```

An interesting issue arises when the script (or matplotlib for that matter) is unable to actually find the ttf-file for the wanted font as in this example on my machine:

```
python3 ./anybadge.py -l "issues not touched since last weeks" -v 100 -s "%" -f Courier.svg -o -n "Courier"
```

It then falls back to using the font metrics of another Font (in my case it was DejaVu Sans):

```
/usr/lib/python3/dist-packages/matplotlib/font_manager.py:1320: UserWarning: findfont: Font family ['Courier'] not found. Falling back to DejaVu Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```
And the result is then wrong as seen in the attached result for this case. I still think that the changes proposed here are a small improvement and would be really greatful if they were considered...

[results.zip](https://github.com/jongracecox/anybadge/files/2781450/results.zip)

### CODE REVIEW

**Comment by jongracecox** [comment]
I'm sorry for not responding sooner to this.  I really like the change and really appreciate you taking the time to make these changes.  My only hesitation is with introducing matplotlib as a dependency.  This feels like a big package to be required when we only need a small part of it.  I wonder whether there are other smaller / more focused packages that achieve the same thing.  What are your thoughts?

**Comment by jongracecox** [comment]
One thought that crossed my mind was that it could be possible to implement this in a way that makes matplotlib optional - for example try to import matplotlib, and if it's not available fall back to the old method.  I'm not a huge fan of this approach, but it is an option.  Thoughts welcome.

**Comment by jongracecox** [comment]
Could you make two more changes and I will merge this:

1. I don't think the `font_width` function is needed any more since it is no longer used.
2. Can you change your commit message to be descriptive of the change you're making (e.g. "Add font option and fix badge width calculations".

**Comment by elbosso** [comment]
As i said - i am new to github - can you point me in the right direction for making the changes you requested - i am unable to find (or google) the right buttons to press to be able to edit the commit message or change the file (remove font_width property and the get_font_width function)

Thanks, Juergen

**Comment by jongracecox** [comment]
> As i said - i am new to github - can you point me in the right direction for making the changes you requested - i am unable to find (or google) the right buttons to press to be able to edit the commit message or change the file (remove font_width property and the get_font_width function)
> 
> Thanks, Juergen

No problem.  I'm new to the github pull request process too.  I'm not sure github has functionality for changing commit messages, so this is something I would do using `git` at the command line.  You could look up how to do an interactive rebase using `git rebase -i origin/master` (you would need to do a `git push --force` after), or maybe this would help: https://help.github.com/en/articles/changing-a-commit-message

I can live without it if you can't get it changed.

Something that occurred to me is that introducing the matplotlib dependency will break for existing users unless it is added to the `setup.py` `install_requires` section.  That would mean anyone pip installing would implicitly get matplotlib installed and the dependency would be satisfied.

**Comment by jongracecox** [comment]
I have added some changes ([summarised here](https://github.com/jongracecox/anybadge/issues/14#issuecomment-497924993)) which may resolve the issues you were seeing.  This doesn't add font support, but it does significantly improve the width calculation without adding in the matplotlib dependency.  I used your code to create a dictionary containing the relative widths of various groups of characters, and then used that to derive the text with.  I think it might still be nice to include the ability to switch fonts, but I'm not sure whether that was your main driver for this change or whether that was a by-product of attempting to fix the width issue.

Please have a try of the 1.2.0 package release and let me know how you get on.

**Comment by jongracecox** [comment]
Closing this PR as I feel it is now redundant given the recent changes in 1.5.

**Pull request closed without merging**
